export const ARENA_SWITCH_ANIMATION_NEXTPRASE =
  "ARENA_SWITCH_ANIMATION_NEXTPRASE";
export const ARENA_SWITCH_ANIMATION_PLAY_NEXT =
  "ARENA_SWITCH_ANIMATION_PLAY_NEXT";
export const ARENA_SWITCH_ANIMATION_PLAY_LATEST =
  "ARENA_SWITCH_ANIMATION_PLAY_LATEST";
export const ARENA_SWITCH_ANIMATION_PLAY_ADD =
  "ARENA_SWITCH_ANIMATION_PLAY_ADD";
export const ARENA_SWITCH_ANIMATION_PLAY_REMOVE =
  "ARENA_SWITCH_ANIMATION_PLAY_REMOVE";
export const ARENA_SWITCH_ANIMATION_PLAY_REPLACE =
  "ARENA_SWITCH_ANIMATION_PLAY_REPLACE";
