export const ARENA_SWITCH_ANIMATION_NEXTPHRASE =
  "ARENA_SWITCH_ANIMATION_NEXTPHRASE";
export const ARENA_SWITCH_ANIMATION_PLAY_NEXT =
  "ARENA_SWITCH_ANIMATION_PLAY_NEXT";
export const ARENA_SWITCH_ANIMATION_PLAY_ADD =
  "ARENA_SWITCH_ANIMATION_PLAY_ADD";
export const ARENA_SWITCH_ANIMATION_PLAY_REMOVE =
  "ARENA_SWITCH_ANIMATION_PLAY_REMOVE";